"""`secret`: set / list the values of `remote` secrets in the local cluster's secret store (ADR-018).

`generate` secrets need nothing: External Secrets Operator creates the values in the cluster. `remote` secrets are read
from the `platform-secrets` store, which locally is the `secrets-store` namespace; values are written there with this
command (from a hidden prompt or stdin) and never touch git. Real clusters use their own store (Vault, AWS, ...).
"""
from __future__ import annotations

import argparse
import getpass
import json
import sys
from pathlib import Path

import gitops
from core import PlatformError, Report, run

STORE_NS = "secrets-store"


def kubectl(args: list[str], input_text: str | None = None) -> str:
    """`kubectl` wrapper (tests replace this)."""
    import subprocess
    proc = subprocess.run(["kubectl", *args], input=input_text, text=True, capture_output=True)
    if proc.returncode != 0:
        raise PlatformError(f"kubectl {' '.join(args[:4])} failed: {(proc.stderr or proc.stdout).strip().splitlines()[-1:]}")
    return proc.stdout


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="cplat secret", description=__doc__)
    sub = p.add_subparsers(dest="action", required=True)
    s = sub.add_parser("set", help="write one value into the local secret store")
    s.add_argument("service")
    s.add_argument("secret", help="secret name as declared in services.yaml")
    s.add_argument("key")
    s.add_argument("--env", default="dev")
    s.add_argument("--value-stdin", action="store_true", help="read the value from stdin instead of prompting")
    l = sub.add_parser("list", help="show declared secrets and whether remote values are present")
    l.add_argument("--env", default="dev")
    for sp in (s, l):
        sp.add_argument("--app")
        sp.add_argument("--repo-dir", default=".")
        sp.add_argument("--context", help="kube context (default k3d-<app>-local)")
    return p


def declared(app_dir: Path) -> list[tuple[dict, dict]]:
    import yaml
    services = (yaml.safe_load((app_dir / "services.yaml").read_text()) or {}).get("services") or []
    return [(svc, sec) for svc in services for sec in svc.get("secrets") or []]


def store_key(app: str, env: str, sec: dict) -> str:
    path = (sec.get("remote") or {}).get("path") or "{app}-{env}-{secret}"
    return str(path).format(app=app, env=env, secret=sec["name"])


def main(argv: list[str]) -> int:
    ns = build_parser().parse_args(argv)
    repo = Path(ns.repo_dir).resolve()
    app_dir = gitops.find_app(repo, ns.app)
    app = app_dir.name
    ctx = ["--context", ns.context or f"k3d-{app}-local"]
    items = declared(app_dir)

    if ns.action == "list":
        r = Report(title=f"secrets of {app} ({ns.env})")
        for svc, sec in items:
            if sec.get("generate"):
                r.did.append(f"{svc['name']}/{sec['name']}: generated by External Secrets Operator ({', '.join(sec['generate'])})")
                continue
            key = store_key(app, ns.env, sec)
            try:
                have = set(json.loads(kubectl([*ctx, "-n", STORE_NS, "get", "secret", key, "-o", "json"])).get("data") or {})
            except PlatformError:
                have = set()
            for k in sec["remote"]["keys"]:
                state = "set" if k in have else f"MISSING → cplat secret set {svc['name']} {sec['name']} {k} --env {ns.env}"
                r.did.append(f"{svc['name']}/{sec['name']}.{k}: {state}")
        if not items:
            r.did.append("no `secrets:` declared (add with `cplat compose add <service> --generate NAME=KEY` or --secret)")
        r.emit(False, False)
        return 0

    match = [sec for svc, sec in items if svc["name"] == ns.service and sec["name"] == ns.secret]
    if not match:
        raise PlatformError(f"{ns.service} has no secret '{ns.secret}'", hint="declared: " + (", ".join(f"{s['name']}/{x['name']}" for s, x in items) or "none"))
    sec = match[0]
    if sec.get("generate"):
        raise PlatformError(f"'{ns.secret}' is generated by External Secrets Operator; there is nothing to set")
    if ns.key not in sec["remote"]["keys"]:
        raise PlatformError(f"'{ns.key}' is not a key of '{ns.secret}'", hint="keys: " + ", ".join(sec["remote"]["keys"]))
    value = sys.stdin.read().rstrip("\n") if ns.value_stdin else getpass.getpass(f"{ns.key} for {ns.service} ({ns.env}): ")
    if not value:
        raise PlatformError("empty value")
    name = store_key(app, ns.env, sec)
    if not _exists(ctx, name):
        kubectl([*ctx, "-n", STORE_NS, "create", "secret", "generic", name])
    kubectl([*ctx, "-n", STORE_NS, "patch", "secret", name, "--type", "merge", "--patch-file", "/dev/stdin"], json.dumps({"stringData": {ns.key: value}}))
    r = Report(title=f"secret {ns.service}/{ns.secret}.{ns.key} ({ns.env})")
    r.did.append(f"stored in {STORE_NS}/{name} (the value is not printed and not in git)")
    r.next_steps.append("ESO syncs it within the refresh interval (default 1h); force it: kubectl annotate externalsecret " + f"{ns.secret} -n {app}-{ns.env} force-sync=$(date +%s) --overwrite")
    r.emit(False, False)
    return 0


def _exists(ctx: list[str], name: str) -> bool:
    try:
        kubectl([*ctx, "-n", STORE_NS, "get", "secret", name])
        return True
    except PlatformError:
        return False
